import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '@styles/Home.module.css'
import styled from '@emotion/styled'
import Button from '@components/Button'

const Home: NextPage = () => {
  return (
    <Wrapper>
      <Head>
        <title>Reaction Speed Test</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Title>Reaction Speed Test</Title>

      <ImageWrapper>
        <Image
          src="/images/main-image.svg"
          alt="Main Image"
          layout="responsive"
          width={100}
          height={100}
        />
      </ImageWrapper>

      <Button />

      <footer>Apple, Inc</footer>
    </Wrapper>
  );
}

const Wrapper = styled.main`
  background: #f6f6f6;
  height: 100vh;
  padding: 1rem 1.5rem;
`;

const Title = styled.h1`
  color: #106048;
  text-align: center;
  font-weight: 600;
  font-size: 1.25rem;
`;

const ImageWrapper = styled.div`
  padding: 3.75rem 2rem;
`

export default Home
